//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Bid { get; set; }
        public string BName { get; set; }
        public string BDesc { get; set; }
        public int Quantity { get; set; }
        public int Categoryid { get; set; }
        public bool Active { get; set; }
        public System.DateTime Createddate { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
