//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Brands = new HashSet<Brand>();
        }
    
        public int Cid { get; set; }
        public string CName { get; set; }
        public string CDes { get; set; }
        public bool Active { get; set; }
        public System.DateTime Createddate { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual ICollection<Brand> Brands { get; set; }
    }
}
