//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int Comid { get; set; }
        public string ComName { get; set; }
        public string ComAdd { get; set; }
        public bool Active { get; set; }
        public System.DateTime Createddate { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
