//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Uid { get; set; }
        public string UName { get; set; }
        public string Single { get; set; }
        public string Box { get; set; }
        public string Carton { get; set; }
        public bool Active { get; set; }
        public System.DateTime LastModified { get; set; }
        public System.DateTime Createddate { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
